import { NavBar } from "@/components";
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Martin Garcia's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="w-full overflow-x-hidden">
      <body className="min-h-dvh w-full overflow-x-hidden bg-[#0B1020] text-[#F6F3EE] selection:bg-[#FF6B6B]/30 selection:text-[#F6F3EE]">
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
